function plotLegend(InVar, vect)
    colour_vect = [0.905, 0.094, 0.698;
                0.278, 0.819, 0.137;
                0.905, 0.772, 0.094;
                0.109, 0.152, 0.949;
                0.258, 0.960, 0.847; ];
    h = zeros(size(colour_vect, 1));
    
    for i=1:length(vect)
        h(i) = plot(NaN, NaN, '-', 'Color', colour_vect(i, :));
    end
    
    equals = ' = ';
    
    if length(vect) == 1     
        legend(char(strcat(InVar, equals, {' '}, num2str(vect(1)))));
    elseif length(vect) == 2
        legend(char(strcat(InVar, equals, {' '}, num2str(vect(1)))), ...
            char(strcat(InVar, equals, {' '}, num2str(vect(2))))...
        );
    elseif length(vect) == 3
        legend(char(strcat(InVar, equals, {' '}, num2str(vect(1)))), ...
            char(strcat(InVar, equals, {' '}, num2str(vect(2)))),...
            char(strcat(InVar, equals, {' '}, num2str(vect(3))))...
        );
    elseif length(vect) == 4
        legend(char(strcat(InVar, equals, {' '}, num2str(vect(1)))), ...
            char(strcat(InVar, equals, {' '}, num2str(vect(2)))),...
            char(strcat(InVar, equals, {' '}, num2str(vect(3)))), ...
            char(strcat(InVar, equals, {' '}, num2str(vect(4))))...
        );
    elseif length(vect) == 5
        legend(char(strcat(InVar, equals, {' '}, num2str(vect(1)))), ...
            char(strcat(InVar, equals, {' '}, num2str(vect(2)))),...
            char(strcat(InVar, equals, {' '}, num2str(vect(3)))), ...
            char(strcat(InVar, equals, {' '}, num2str(vect(4)))), ...
            char(strcat(InVar, equals, {' '}, num2str(vect(5))))...
        );
    end
end
